### PR TITLE
support loadJsonContent function

### PR DESCRIPTION
**Pull request by johannesclaesson**
Add support for loadJsonContent function.

### CODE REVIEW

**Review by gruebel — APPROVED** [review]
great work, thanks for the contribution 🚀 I planed to tackle both the new function and the new single line syntax this weekend, but you beat me to it 😄

**Comment by gruebel** [comment]
I'm curious, how was it to create the PR? Did you have some problems to understand the project structure or some other challenges, which I could mention in the docs?

**Comment by johannesclaesson** [comment]
> I'm curious, how was it to create the PR? Did you have some problems to understand the project structure or some other challenges, which I could mention in the docs?
I forgot to re-run the pre-commit scripts before creating the pull request, missing out on a bug. I just made my edits until the existing and my new pytest tests passed. Maybe a `poetry test all` or something similar would mitigate such mistakes.

Other than that, the code itself was easy enough to figure out, given that similar code already existed, and I could simply combine what was present for the other tokens.

**Comment by gruebel** [comment]
nice and thanks for the feedback!

**Pull request merged**
